//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyScreenSaver.Languages {
    using System;
    
    
    /// <summary>
    ///   Yerelleştirilmiş dizeleri aramak gibi işlemler için, türü kesin olarak belirtilmiş kaynak sınıfı.
    /// </summary>
    // Bu sınıf ResGen veya Visual Studio gibi bir araç kullanılarak StronglyTypedResourceBuilder
    // sınıfı tarafından otomatik olarak oluşturuldu.
    // Üye eklemek veya kaldırmak için .ResX dosyanızı düzenleyin ve sonra da ResGen
    // komutunu /str seçeneğiyle yeniden çalıştırın veya VS projenizi yeniden oluşturun.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Bu sınıf tarafından kullanılan, önbelleğe alınmış ResourceManager örneğini döndürür.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyScreenSaver.Languages.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Tümü için geçerli iş parçacığının CurrentUICulture özelliğini geçersiz kular
        ///   CurrentUICulture özelliğini tüm kaynak aramaları için geçersiz kılar.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ekle benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tümünü Kaldır benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string AllRemove {
            get {
                return ResourceManager.GetString("AllRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Varsayılan benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Default {
            get {
                return ResourceManager.GetString("Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Dosyayı listeden çıkartmak istiyor musun? benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Delete_File_List {
            get {
                return ResourceManager.GetString("Delete_File_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Düzenle benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hata benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   HATA: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ERROR_2 {
            get {
                return ResourceManager.GetString("ERROR_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   \bHATA  benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ERROR_FILE {
            get {
                return ResourceManager.GetString("ERROR_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Müzik Yok. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ERROR_NoMusic {
            get {
                return ResourceManager.GetString("ERROR_NoMusic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Resim Yok. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ERROR_NoPicture {
            get {
                return ResourceManager.GetString("ERROR_NoPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fareyle çift tıklatıldığında çık benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ExitMouseDbClick {
            get {
                return ResourceManager.GetString("ExitMouseDbClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dosya Türleri benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string FileTypes {
            get {
                return ResourceManager.GetString("FileTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   VLC&apos;yi Düzelt benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string FixVLC {
            get {
                return ResourceManager.GetString("FixVLC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Genel Ayarlar benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string GeneralSettings {
            get {
                return ResourceManager.GetString("GeneralSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Resim Slayt Gösterisi benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ImageSlideshow {
            get {
                return ResourceManager.GetString("ImageSlideshow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dil benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Resim Klasör Listesi benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ListofImageFolders {
            get {
                return ResourceManager.GetString("ListofImageFolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Müzik Klasör Listesi benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ListofMusicFolders {
            get {
                return ResourceManager.GetString("ListofMusicFolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Video Klasör Listesi benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ListofVideoFolders {
            get {
                return ResourceManager.GetString("ListofVideoFolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Yükleniyor... benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Müzik Oynatıcısı benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string MusicPlayer {
            get {
                return ResourceManager.GetString("MusicPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Müzik Oynatıcısı Etkin benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string MusicPlayerEnabled {
            get {
                return ResourceManager.GetString("MusicPlayerEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tamam benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &amp;Güncelleme Yöneticisini Aç benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string OpenUpdateManager {
            get {
                return ResourceManager.GetString("OpenUpdateManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Resimleri slayt gösterisi olarak oynat benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string PictureAuto {
            get {
                return ResourceManager.GetString("PictureAuto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tüm listeden çıkarmaları &quot;Evet&quot; olarak hatırla benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string RememberRemoveFileList {
            get {
                return ResourceManager.GetString("RememberRemoveFileList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kaldır benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dosyayı Kaldır benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string RemoveFile {
            get {
                return ResourceManager.GetString("RemoveFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   saniye benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string seconds {
            get {
                return ResourceManager.GetString("seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ayarlar benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Göster benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Show {
            get {
                return ResourceManager.GetString("Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Saati ve Tarihi Göster benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ShowClockAndDate {
            get {
                return ResourceManager.GetString("ShowClockAndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Süreyi Göster benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ShowTime {
            get {
                return ResourceManager.GetString("ShowTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Süre: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Süre benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string TTime {
            get {
                return ResourceManager.GetString("TTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   URL: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string URL {
            get {
                return ResourceManager.GetString("URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Video Slayt Gösterisi benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string VideoSlideshow {
            get {
                return ResourceManager.GetString("VideoSlideshow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   VLC Media Player benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string VLC {
            get {
                return ResourceManager.GetString("VLC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Desteklenen Web Siteler: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string VLC_SupportedWebsites {
            get {
                return ResourceManager.GetString("VLC_SupportedWebsites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   VLC URL Listesi benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string VLCURLList {
            get {
                return ResourceManager.GetString("VLCURLList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Windows Media Player benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string WMP {
            get {
                return ResourceManager.GetString("WMP", resourceCulture);
            }
        }
    }
}
